package mesh;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class Export {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void export() {
		System.out.println("1...");
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
		vars.put("VarPwd", "gath3r3r");
		vars.put("VarFromDay", "10");
		vars.put("VarFromYear", "2024");
		vars.put("VarFromMonth", "6");
		System.out.println("2...");
		driver.get("https://online.asb.co.nz/auth/authn?goto=https://online.asb.co.nz/fnc");
		driver.manage().window().setSize(new Dimension(1032, 850));
		driver.findElement(By.id("dUsername")).sendKeys("patfada");
		driver.findElement(By.id("password")).click();
		driver.findElement(By.id("password")).sendKeys(vars.get("VarPwd").toString());
		driver.findElement(By.cssSelector(".logon-button__label")).click();
		driver.switchTo().frame(1);
		driver.findElement(By.cssSelector("#account-123140013110200 .icon-details-card-layout_details__1mgdG")).click();
		driver.switchTo().defaultContent();
		driver.findElement(By.cssSelector("td:nth-child(4) .scw_table td:nth-child(2)")).click();
		driver.findElement(By.id("Request_FromDate_inputDate")).click();
		driver.findElement(By.cssSelector(".StatementSelectorControlsWrap")).click();
		driver.findElement(By.id("Request_FromDate_inputDate")).sendKeys(vars.get("VarFromDay").toString());
		driver.findElement(By.id("Request_FromDate_inputMonth")).sendKeys(vars.get("VarFromMonth").toString());
		driver.findElement(By.id("Request_FromDate_inputYear")).sendKeys(vars.get("VarFromYear").toString());
		driver.findElement(By.id("ExportFormatDropdown_input")).click();
		driver.findElement(By.cssSelector("#ExportFormatDropdown_input_4 > .leftDisplay")).click();
		driver.switchTo().frame(1);
		driver.findElement(By.cssSelector("#main-menu-button > .label")).click();
		driver.switchTo().defaultContent();
		driver.switchTo().frame(2);
		{
			WebElement element = driver.findElement(By.cssSelector(".label:nth-child(2)"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).perform();
		}
		{
			WebElement element = driver.findElement(By.tagName("body"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element, 0, 0).perform();
		}
		driver.findElement(By.linkText("View accounts")).click();
		driver.switchTo().defaultContent();
		driver.switchTo().frame(1);
		driver.findElement(By.cssSelector(".style_smalloutlined__35ZOQ")).click();
		driver.findElement(By.cssSelector("#account-XXXXXXXXXXXX8128 .overline")).click();
		driver.switchTo().defaultContent();
		driver.findElement(By.linkText("Search & Export")).click();
		driver.findElement(By.id("Request_FromDate_inputDate")).click();
		driver.findElement(By.id("Request_FromDate_inputDate")).click();
		{
			WebElement element = driver.findElement(By.id("Request_FromDate_inputDate"));
			Actions builder = new Actions(driver);
			builder.doubleClick(element).perform();
		}
		driver.findElement(By.id("Request_FromDate_inputDate")).sendKeys(vars.get("VarFromDay").toString());
		driver.findElement(By.id("Request_FromDate_inputMonth")).sendKeys(vars.get("VarFromMonth").toString());
		driver.findElement(By.id("Request_FromDate_inputYear")).sendKeys(vars.get("VarFromYear").toString());
		driver.findElement(By.cssSelector(".statementSelectorWrap")).click();
		driver.findElement(By.id("ExportFormatDropdown_input")).click();
		driver.findElement(By.cssSelector("#ExportFormatDropdown_input_4 > .leftDisplay")).click();

	}
}
