package mesh.budget.controller;

import javafx.fxml.FXML;
import javafx.scene.control.TextField;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;
import mesh.budget.model.BankStatementRow;
import mesh.budget.model.Budget;
import javafx.event.ActionEvent;

public class AddMatchController {

	private Budget budget;

	@FXML
	private AnchorPane anchorPane;

	@FXML
	private TextField matchText;

	// Event Listener on Button.onAction
	@FXML
	public void addMatch(ActionEvent event) {
		// TODO Autogenerated
	}

	public AddMatchController(Budget budget) {
		this.budget = budget;

	}

	public void show(String description) {

		Stage stage = (Stage) anchorPane.getScene().getWindow();

		matchText.setText(description);

		stage.show();
	}

}
