package mesh.budget.controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.MenuItem;

import javafx.scene.control.Tab;

import javafx.event.Event;

import javafx.scene.control.TableView;

public class tempController {
	@FXML
	private MenuItem loadmenu;
	@FXML
	private MenuItem savemenu1;
	@FXML
	private Button labeutton1l1;
	@FXML
	private TableView table1;
	@FXML
	private Tab charttab;

	// Event Listener on MenuItem[#loadmenu].onAction
	@FXML
	public void loadExports(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#savemenu1].onAction
	@FXML
	public void save(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void showCategoryManager(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void runMatches(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#labeutton1l1].onAction
	@FXML
	public void HelloButtonClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Tab.onSelectionChanged
	@FXML
	public void onSelectChartTab(Event event) {
		// TODO Autogenerated
	}
}
